name: taniak
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  cloud_firestore: ^3.1.10
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  fluttertoast: ^8.0.9
  flutter_svg: ^0.22.0
  flutter_bloc: ^8.0.1
  get: ^4.6.1
  font_awesome_flutter: ^8.8.1
  carousel_slider: ^4.0.0
  flutter_icons: ^1.1.0
  equatable: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/